### ISSUE TITLE
mdpi website triggers downloads for PDF

### ISSUE THREAD

**Issue by targos** [cheminfo/molbank#1]
Because of that we have to use a proxy to be able to display the document in an iframe

**Comment by lpatiny** [comment]
We would like to display in an IFRAME directly the pdf of the artcile. But currently the link you have for an article: http://www.mdpi.com/1422-8599/2016/2/M898/pdf
Systematically triggers the download. This is due to the Content-Disposition header that you add. This is quite the behaviour you would like from you website but not what we would like to display the article in an iframe.
Is it possible to have a link that would not add this Content-Disposition ? For example: http://www.mdpi.com/1422-8599/2016/2/M898/viewpdf

![image](https://cloud.githubusercontent.com/assets/1484241/15602081/6a82fe4c-23f3-11e6-9555-c3245db9a454.png)

**Comment by ghost** [comment]
Hi Luc, this should work if you set the following GET parameter:
'view' = 'inline'

For the given example, this works:
http://www.mdpi.com/1422-8599/2016/2/M898/pdf?view=inline

**Comment by targos** [comment]
The inline link works but we cannot use it because of the browser's content security policy.
Our website is `https` and it therefore cannot access `http` resources.
https://www.mdpi.com/1422-8599/2016/2/M898/pdf?view=inline redirects to the insecure version of the website.

**Comment by ghost** [comment]
We do not offer https on mdpi.com due to the CDN usage for the clients in US. All the content on mdpi.com is open source and there is no login data transiting there.

If you need the pdf version of all our Molbank articles, I can do the same as for the XMLs, deposit them here in a zip archive.

**Comment by targos** [comment]
The application is ready but the `inline` url does not work anymore. Instead we are redirected to the article page.

**Comment by ghost** [comment]
Hi Michael, we have setup a captcha page for people trying to download our XML articles.
Would it make sense if we remove the captcha for your static IP if you have one?

**Comment by lpatiny** [comment]
But in our case we only try to display the PDF of the article, not the XML

In instance: www.mdpi.com/1422-8599/2017/3/M957/pdf

**Comment by ghost** [comment]
Sorry for that, a mistake from one of our devs, it is now removed.

**Comment by targos** [comment]
Thanks.
